# Generated by Django 4.0.3 on 2022-03-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_updated_at_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
